### ISSUE TITLE
Install neutron-metadata agent on every node

### ISSUE THREAD

**Issue by mandeepdhami** [noironetworks/fuel-plugin-cisco-aci#3]
1. To enable optimized metadata, neutron-metadata agent needs to be installed on every node.
2. While metadata-agent must be installed, it should not be enabled as a service
3. The configuration should be updated so that 'metadata_workers = 2'

(Ratnakar forward to Mirantis after any updates)

**Comment by ratnakark** [comment]
Fixed.
